// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlReleaseManager.Core.Persistence;

#nullable disable

namespace SqlReleaseManager.Core.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.DatabaseInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeploymentConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SqlServerInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentConfigurationId");

                    b.HasIndex("SqlServerInstanceId");

                    b.ToTable("DatabaseInstances");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatabaseInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("DeploymentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseInstanceId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.DeploymentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeploymentConfigurations");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.SqlServerInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SqlServerInstances");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.DatabaseInstance", b =>
                {
                    b.HasOne("SqlReleaseManager.Core.Persistence.DeploymentConfiguration", "DeploymentConfiguration")
                        .WithMany()
                        .HasForeignKey("DeploymentConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlReleaseManager.Core.Persistence.SqlServerInstance", "SqlServerInstance")
                        .WithMany("Databases")
                        .HasForeignKey("SqlServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentConfiguration");

                    b.Navigation("SqlServerInstance");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.Deployment", b =>
                {
                    b.HasOne("SqlReleaseManager.Core.Persistence.DatabaseInstance", "DatabaseInstance")
                        .WithMany("Deployments")
                        .HasForeignKey("DatabaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseInstance");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.DatabaseInstance", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("SqlReleaseManager.Core.Persistence.SqlServerInstance", b =>
                {
                    b.Navigation("Databases");
                });
#pragma warning restore 612, 618
        }
    }
}
