version: '3.4'

services:
  sqlreleasemanager.web:
    image: ${DOCKER_REGISTRY-}sqlreleasemanagerweb
    build:
      context: .
      dockerfile: src/SqlReleaseManager.Web/Dockerfile
    environment:
      - ConnectionStrings__ApplicationDb=Server=sqlserver;Database=SqlReleaseManager;User Id=sa;Password=Password123;Trust Server Certificate=True;
      - ConnectionStrings__IdentityDb=Server=sqlserver;Database=SqlReleaseManager;User Id=sa;Password=Password123;Trust Server Certificate=True;
      - Database__RunMigrationsOnStartup=true
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver:/var/opt/mssql
volumes:
  sqlserver:


