version: '3.4'

services:
  sqlreleasemanager.web:
    image: ${DOCKER_REGISTRY-}sqlreleasemanagerweb
    build:
      context: .
      dockerfile: src/SqlReleaseManager.Web/Dockerfile
  sqlserver: 
    image: microsoft/mssql-server-linux:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
